all: q1 q2 q3 q4 q5

q1: q1.c
	gcc -g -Wall -Wextra -std=c99 -pthread q1.c -o q1

q2: q2.c
	gcc -g -Wall -Wextra -std=c99 -pthread q2.c -o q2

q3: q3.c
	gcc -g -Wall -Wextra -std=c99 -pthread q3.c -o q3

q4: q4.c
	gcc -g -Wall -Wextra -std=c99 -pthread q4.c -o q4

q5: q5.c
	gcc -g -Wall -Wextra -std=c99 -pthread q5.c -o q5